import { test, expect } from '@playwright/test'

test('login, devices, conjunctive filters, download, settings and mobile layout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('密码', { exact: true }).fill('browser-test-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '存储总览', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '摄像机管理', exact: true }).click()
  await page.getByRole('button', { name: '添加摄像机', exact: true }).click()
  await page.getByLabel('设备名称').fill('后院摄像机')
  await page.getByLabel('原录像保留天数').fill('14')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('heading', { name: '摄像机接入信息' })).toBeVisible()
  await page.getByRole('button', { name: '已保存接入信息' }).click()
  await expect(page.getByRole('heading', { name: '后院摄像机', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '录像文件', exact: true }).click()
  await page.getByLabel('相机编号 X').fill('00')
  await page.getByLabel('指定日期').fill('2025-10-08')
  await page.getByLabel('年份').fill('2025')
  await page.getByLabel('月份').selectOption('10')
  await page.getByLabel('视频类型').selectOption('original')
  const row = page.getByRole('row').filter({ hasText: '00_20251008080000_20251008080100.mp4' })
  await expect(row).toBeVisible()
  const pending = page.waitForEvent('download')
  await row.getByRole('link').click()
  const download = await pending
  expect(await download.failure()).toBeNull()
  await page.getByLabel('相机编号 X').fill('0')
  await expect(page.getByText('没有符合条件的录像')).toBeVisible()
  await page.getByLabel('相机编号 X').fill('00')
  await expect(row).toBeVisible()
  await page.screenshot({ path: '/tmp/cammon-files.png', fullPage: true })
  await page.getByRole('button', { name: '真实存储', exact: true }).click()
  await expect(page.getByRole('heading', { name: '元数据数据库' })).toBeVisible()
  await expect(page.getByText('尚未配置 · 仅内存运行')).toBeVisible()
  await page.getByRole('button', { name: /NFS/ }).click()
  await expect(page.getByLabel('NFS 版本')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: '/tmp/cammon-mobile.png', fullPage: true })
  expect(errors).toEqual([])
})
